### ISSUE TITLE
Plan construction failed.

### ISSUE THREAD

**Issue by masterdezign** [mstksg/inCode#11]
Hello Justin!

Guided by your blog post about backprop, I am running

> $ ./intro-backprop.hs
> Plan construction failed.

How can I debug that? 

https://github.com/mstksg/inCode/blob/44faf147d60c28094259618bc2969cca699d12c9/code-samples/backprop/intro-backprop.hs#L2

**Comment by masterdezign** [comment]
>  $ stack --version
> Version 1.6.3 x86_64 hpack-0.20.0

Oh, now I see

> $ stack --install-ghc exec ghc --resolver lts-10.4 --package split --package mwc-random --package one-liner-instances --package ANum --package backprop-0.1.2.0 --package hmatrix-vector-sized --package hmatrix-backprop --package lens --package mnist-idx -- -Wall -O2
> 
> Error: While constructing the build plan, the following exceptions were
> encountered:
> 
> Unknown package: hmatrix-backprop
> 
> Unknown package: hmatrix-vector-sized

I would be much more informative to see this information immediately when plan construction failed.

**Comment by masterdezign** [comment]
Running `$ stack update` seems to have resolved the issue

**Comment by mstksg** [comment]
Thanks for catching this!  I'll be sure to add this as a note.
