### ISSUE TITLE
 two-layer model fails to learn XOR

### ISSUE THREAD

**Issue by vincent-hui** [mstksg/inCode#17]
In the blog post
https://blog.jle.im/entry/purely-functional-typed-models-1.html
The last training sample of XOR is not correct
```
samps = [(H.vec2 0 0, 0), (H.vec2 1 0, 1), (H.vec2 0 1, 1), (H.vec2 1 1, 1)]
```
The training samples should be
```
samps = [(H.vec2 0 0, 0), (H.vec2 1 0, 1), (H.vec2 0 1, 1), (H.vec2 1 1, 0)]
```
After training,  two-layer model fails to learn XOR
```
*Main H> twoLayer = (feedForwardLog' @4 <~ feedForwardLog') :: Model _ (R 2) (R 1)
*Main H> samps = [(H.vec2 0 0, 0 :: R 1), (H.vec2 1 0, 1 :: R 1), (H.vec2 0 1, 1 :: R 1), (H.vec2 1 1, 0 :: R 1)]
*Main H> trained <- trainModelIO twoLayer $ take 10000 (cycle samps)
*Main H> evalBP2 twoLayer trained (H.vec2 0 0)
(0.4979878920542456 :: R 1)
*Main H> evalBP2 twoLayer trained (H.vec2 1 0)
(0.5009527876478944 :: R 1)
*Main H> evalBP2 twoLayer trained (H.vec2 0 1)
(0.49942779533547044 :: R 1)
*Main H> evalBP2 twoLayer trained (H.vec2 1 1)
(0.5022570085379883 :: R 1)
```

**Comment by mstksg** [comment]
Ah, thanks for pointing it out.  I think I probably trained with the right samples, but had a typo in the blog text.  However, I do remember things working out when I tried it like the post suggests.  What happens when you try taking more samples?

**Comment by vincent-hui** [comment]
Thank you.
Two-layer model can learn XOR by taking more samples. ```trained <- trainModelIO twoLayer $ take 50000 (cycle samps)```

**Comment by mstksg** [comment]
Ah interesting, thanks :)  I'll update the post to reflect this too.
