### ISSUE TITLE
The example does not work

### ISSUE THREAD

**Issue by onurcanbektas** [mstksg/inCode#21]
The [example](https://github.com/mstksg/inCode/blob/master/code-samples/backprop/intro-backprop.hs#L14-L16) when it is run, gives the following error:

```
• Could not deduce (Backprop Net) arising from a use of ‘^^.’
      from the context: Reifies s W
        bound by the type signature for:
                   runNet :: forall s.
                             Reifies s W =>
                             BVar s Net -> BVar s (R 784) -> BVar s (R 10)
        at app/Main.hs:(48,1)-(52,20)
    • In the first argument of ‘(#>)’, namely ‘(n ^^. weights1)’
      In the first argument of ‘(+)’, namely ‘(n ^^. weights1) #> x’
      In the second argument of ‘($)’, namely
        ‘(n ^^. weights1) #> x + (n ^^. bias1)’
   |
55 |     y = logistic $ (n ^^. weights1) #> x + (n ^^. bias1)
   |                     ^^^^^^^^^^^^^^
```

**Comment by mstksg** [comment]
Ah, how are you running it?

I did notice that since the LTS has moved on, you need to explicitly specify `hmatrix-backprop-0.1.0.0` in the stack call at the top.  But with that change it should build fine.  The error you are showing, however, seems to suggest you're using *backprop-0.2*; the example is only compatible with *backprop-0.1*, so the blog post is a bit out of date.  I should probably mark that, so thanks for the heads up!

In the meanwhile, the [official backprop website](https://backprop.jle.im/) might have a better introduction, if you are looking to get started :)

**Comment by onurcanbektas** [comment]
Even with the version `0.1`, the error is still the same 

```
    • Could not deduce (Backprop Net) arising from a use of ‘^^.’
      from the context: Reifies s W
        bound by the type signature for:
                   runNet :: forall s.
                             Reifies s W =>
                             BVar s Net -> BVar s (R 784) -> BVar s (R 10)
        at app/Main.hs:(48,1)-(52,20)
    • In the first argument of ‘(#>)’, namely ‘(n ^^. weights1)’
      In the first argument of ‘(+)’, namely ‘(n ^^. weights1) #> x’
      In the second argument of ‘($)’, namely
        ‘(n ^^. weights1) #> x + (n ^^. bias1)’
   |
55 |     y = logistic $ (n ^^. weights1) #> x + (n ^^. bias1)
   |                     ^^^^^^^^^^^^^^


--  While building package fallacyOfCommon-0.1.0.0 using:
```

Thanks for the link; let me also look at it.

**Comment by mstksg** [comment]
Are you running it using the stack shebang?

```
$ ./thefilename.hs
```

The stack shebang at the top makes the script itself an executable that can be called from the command line.  This ensures the proper versions of everything are loaded.

**Comment by onurcanbektas** [comment]
I was building it using stack instead.  The shebang is there but when I try to execute from the console `$ ./Main.hs`, it first give permission denied error and if I use `sudo`, it just gives `command not found`.

**Comment by mstksg** [comment]
Ah, yeah, i believe you'd have to set the file as executable if you want to execute it directly

```
$ chmod u+x Main.hs
```

I could probably work on the usability aspects of these scripts a bit more admittedly :)
